[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "opencv-python>=4.11.0.86",
    "py2neo>=2021.2.4",
    "pytesseract>=0.3.13",
    "tesseract==0.1.3",
]
